const categories = [
  ['tourist-place','Tourist places','⌂','#ff7956'], ['restaurant','Restaurants','⌑','#ffb31f'], ['food-drink','Bars & pubs','♨','#ff6b92'], ['sports','Sports events','◉','#70c8ae'], ['music','Music events','♫','#8a80e8'], ['experience','Experiences & tours','↝','#ffa35b'], ['theatre-comedy','Theatre & comedy','◒','#be77e6'], ['market-shopping','Markets & shopping','▦','#e6953b'], ['parks-outdoors','Parks & outdoors','♧','#67bd6e'], ['family-kids','Family & kids','★','#61b9e8'], ['art-culture','Art, history & culture','◈','#8676cf'], ['seasonal-free','Seasonal & free events','☼','#ed6c5d'], ['wellness-indoor','Wellness & rainy-day','☯','#6fb8b0'], ['visitor-services','Visitor services','ⓘ','#617994']
].map(([id,label,icon,color]) => ({id,label,icon,color}));
const categoryById = Object.fromEntries(categories.map(c => [c.id,c]));

// Curated, real London locations. Live city updates are fetched by the local server.
const items = [
  {id:'british-museum',categories:['tourist-place','art-culture'],name:'The British Museum',summary:'National museum with collections spanning human history, art and culture.',area:'Bloomsbury',address:'Great Russell Street, WC1B 3DG',lat:51.5194,lng:-0.1270,hours:'Daily · 10:00–17:00',open:true,free:true,family:true,stepfree:true,indoor:true,station:'Tottenham Court Road · 5 min',price:'Free entry',source:'The British Museum',sourceLink:'https://www.britishmuseum.org/',verified:'Check the venue website for today’s hours'},
  {id:'borough-market',categories:['restaurant','market-shopping'],name:'Borough Market',summary:'Historic food market beside London Bridge, with traders, restaurants and takeaway stalls.',area:'South Bank',address:'8 Southwark Street, SE1 1TL',lat:51.5055,lng:-0.0910,hours:'Opening times vary by trader',open:true,indoor:true,station:'London Bridge · 3 min',price:'Varies',source:'Borough Market',sourceLink:'https://boroughmarket.org.uk/',verified:'Check the market website before visiting'},
  {id:'hyde-park',categories:['family-kids','parks-outdoors'],name:'Hyde Park',summary:'One of London’s Royal Parks, with Serpentine Lake, memorials and broad walking routes.',area:'Kensington',address:'Hyde Park, W2',lat:51.5073,lng:-0.1657,hours:'Daily · 05:00–00:00',open:true,free:true,family:true,stepfree:true,station:'Hyde Park Corner · 5 min',price:'Free entry',source:'The Royal Parks',sourceLink:'https://www.royalparks.org.uk/visit/parks/hyde-park',verified:'Check park notices before visiting'},
  {id:'royal-opera-house',categories:['theatre-comedy','experience'],name:'Royal Opera House',summary:'Covent Garden venue presenting opera, ballet and a programme of performances and tours.',area:'Covent Garden',address:'Bow Street, WC2E 9DD',lat:51.5133,lng:-0.1213,hours:'Performance times vary',open:true,indoor:true,station:'Covent Garden · 2 min',price:'Ticketed events',event:true,eventWeekdays:[2,3,4,5,6],source:'Royal Opera House',sourceLink:'https://www.roh.org.uk/',verified:'See the live programme and box office'},
  {id:'ronnie-scotts',categories:['music'],name:'Ronnie Scott’s Jazz Club',summary:'Soho jazz club with evening live music and a restaurant.',area:'Soho',address:'47 Frith Street, W1D 4HT',lat:51.5137,lng:-0.1330,hours:'Evening performances',open:true,indoor:true,station:'Tottenham Court Road · 5 min',price:'Ticketed events',event:true,eventWeekdays:[0,1,2,3,4,5,6],source:'Ronnie Scott’s',sourceLink:'https://www.ronniescotts.co.uk/',verified:'See the live programme and box office'},
  {id:'greenwich-park',categories:['sports','parks-outdoors','seasonal-free'],name:'Greenwich Park',summary:'Historic Royal Park with views across the Thames, the Royal Observatory and formal gardens.',area:'Greenwich',address:'Greenwich, SE10 8EJ',lat:51.4769,lng:0.0005,hours:'Daily · 06:00–21:00',open:true,free:true,family:true,stepfree:true,station:'Greenwich · 12 min',price:'Free entry',source:'The Royal Parks',sourceLink:'https://www.royalparks.org.uk/visit/parks/greenwich-park',verified:'Check park notices before visiting'},
  {id:'london-eye',categories:['experience','tourist-place'],name:'The London Eye',summary:'Riverside observation wheel with panoramic views across central London.',area:'South Bank',address:'Riverside Building, County Hall, SE1 7PB',lat:51.5033,lng:-0.1195,hours:'Opening times vary',open:true,station:'Waterloo · 5 min',price:'Ticketed attraction',source:'The London Eye',sourceLink:'https://www.londoneye.com/',verified:'Book and check times with the attraction'},
  {id:'wellcome-collection',categories:['wellness-indoor','art-culture'],name:'Wellcome Collection',summary:'Free museum and library exploring health, medicine and human experience.',area:'Bloomsbury',address:'183 Euston Road, NW1 2BE',lat:51.5224,lng:-0.1358,hours:'Tue–Sun · 10:00–18:00',open:true,free:true,stepfree:true,indoor:true,station:'Euston Square · 2 min',price:'Free entry',source:'Wellcome Collection',sourceLink:'https://wellcomecollection.org/',verified:'Check the venue website for today’s hours'},
  {id:'spitalfields-market',categories:['market-shopping','art-culture'],name:'Old Spitalfields Market',summary:'Covered market with independent shops, food traders and regular markets.',area:'Shoreditch',address:'16 Horner Square, E1 6EW',lat:51.5196,lng:-0.0753,hours:'Daily · 10:00–20:00',open:true,stepfree:true,indoor:true,station:'Liverpool Street · 5 min',price:'Free to browse',source:'Old Spitalfields Market',sourceLink:'https://oldspitalfieldsmarket.com/',verified:'Check individual trader times'},
  {id:'camden-market',categories:['restaurant','parks-outdoors'],name:'Camden Market',summary:'Food, shopping and canalside spaces across Camden’s market district.',area:'Camden',address:'54–56 Camden Lock Place, NW1 8AF',lat:51.5416,lng:-0.1450,hours:'Daily · 10:00–18:00',open:true,family:true,station:'Camden Town · 5 min',price:'Free to browse',source:'Camden Market',sourceLink:'https://camdenmarket.com/',verified:'Check individual trader times'},
  {id:'visit-london-centre',categories:['visitor-services'],name:'London Visitor Centre',summary:'Visitor information point in the heart of Westminster, close to Trafalgar Square.',area:'Westminster',address:'Regent Street, SW1Y 5AH',lat:51.5084,lng:-0.1310,hours:'Hours vary',open:true,free:true,stepfree:true,indoor:true,station:'Piccadilly Circus · 3 min',price:'Free service',source:'Visit London',sourceLink:'https://www.visitlondon.com/',verified:'Check visitor information before travelling'},
  {id:'barbican-centre',categories:['music','art-culture'],name:'Barbican Centre',summary:'Arts centre with concerts, theatre, cinema, galleries and public spaces.',area:'City of London',address:'Silk Street, EC2Y 8DS',lat:51.5200,lng:-0.0938,hours:'Programme times vary',open:true,indoor:true,stepfree:true,station:'Barbican · 2 min',price:'Free galleries and ticketed events',event:true,eventWeekdays:[1,2,3,4,5,6],source:'Barbican',sourceLink:'https://www.barbican.org.uk/',verified:'See the live programme and venue opening times'},
  {id:'somerset-house',categories:['seasonal-free','family-kids','art-culture'],name:'Somerset House',summary:'Neoclassical arts centre on the Strand with exhibitions, events and a public courtyard.',area:'Westminster',address:'Strand, WC2R 1LA',lat:51.5115,lng:-0.1178,hours:'Opening times vary',open:true,family:true,stepfree:true,station:'Temple · 6 min',price:'Free courtyard; events vary',event:true,eventWeekdays:[0,1,2,3,4,5,6],source:'Somerset House',sourceLink:'https://www.somersethouse.org.uk/',verified:'See the live programme and venue opening times'},
  {id:'national-gallery',categories:['tourist-place','art-culture'],name:'The National Gallery',summary:'Trafalgar Square gallery with a major collection of Western European paintings.',area:'Westminster',address:'Trafalgar Square, WC2N 5DN',lat:51.5089,lng:-0.1283,hours:'Daily · 10:00–18:00',open:true,free:true,indoor:true,station:'Charing Cross · 2 min',price:'Free entry',source:'The National Gallery',sourceLink:'https://www.nationalgallery.org.uk/',verified:'Check the venue website for today’s hours'},
  {id:'nancy-spains',categories:['food-drink'],name:'Nancy Spains Shoreditch',summary:'Kerry-family-run Irish pub with live music, food and traditional Irish music.',area:'Shoreditch',address:'128–130 Curtain Road, EC2A 3AQ',lat:51.5245,lng:-0.0807,hours:'Hours vary',open:true,indoor:true,station:'Shoreditch High Street · 5 min',price:'££',isPub:true,source:'Nancy Spains',sourceLink:'https://nancyspains.co.uk/',verified:'Check the venue website before visiting'},
  {id:'dishoom-covent-garden',categories:['restaurant'],name:'Dishoom Covent Garden',summary:'Bombay-inspired all-day café serving breakfast, small plates, grills and cocktails.',area:'Covent Garden',address:'12 Upper St Martin’s Lane, WC2H 9FB',lat:51.5138,lng:-0.1266,hours:'Daily · Hours vary',open:true,indoor:true,station:'Covent Garden · 4 min',price:'££',source:'Tripadvisor',sourceLink:'https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d1863498-Reviews-Dishoom_Covent_Garden-London_England.html',verified:'Listed on Tripadvisor; check the restaurant for current queue and booking details'},
  {id:'kiln',categories:['restaurant'],name:'Kiln',summary:'Live-fire Thai cooking and sharing plates in a compact Soho dining room.',area:'Soho',address:'58 Brewer Street, W1F 9TL',lat:51.5128,lng:-0.1345,hours:'Daily · Hours vary',open:true,indoor:true,station:'Piccadilly Circus · 5 min',price:'££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/best-restaurants-in-london/',verified:'Included in SquareMeal’s London restaurant coverage; check walk-in and booking availability'},
  {id:'the-barbary',categories:['restaurant'],name:'The Barbary',summary:'North African and Middle Eastern-inspired counter dining beside Neal’s Yard.',area:'Covent Garden',address:'16 Neal’s Yard, WC2H 9DP',lat:51.5147,lng:-0.1264,hours:'Daily · Hours vary',open:true,indoor:true,station:'Covent Garden · 3 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/best-restaurants-in-london/',verified:'Included in SquareMeal’s London restaurant coverage; check reservations before visiting'},
  {id:'noble-rot-soho',categories:['restaurant','food-drink'],name:'Noble Rot Soho',summary:'Wine bar and restaurant with a broad cellar, seasonal French-leaning plates and walk-in bar seating.',area:'Soho',address:'6 Greek Street, W1D 4DE',lat:51.5133,lng:-0.1318,hours:'Daily · Hours vary',open:true,indoor:true,station:'Tottenham Court Road · 5 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best/londons-top-100-restaurants_262',verified:'Featured in SquareMeal’s London Top 100 coverage; check current service times'},
  {id:'brat',categories:['restaurant'],name:'Brat',summary:'Shoreditch restaurant known for Basque-influenced cooking and wood-grilled seafood.',area:'Shoreditch',address:'4 Redchurch Street, E1 6JL',lat:51.5239,lng:-0.0781,hours:'Daily · Hours vary',open:true,indoor:true,station:'Shoreditch High Street · 4 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best/londons-top-100-restaurants_262',verified:'Featured in SquareMeal’s London Top 100 coverage; check reservations before visiting'},
  {id:'st-john-smithfield',categories:['restaurant'],name:'St. John',summary:'Landmark Smithfield restaurant for unfussy British cooking and a celebrated bakery.',area:'City of London',address:'26 St John Street, EC1M 4AY',lat:51.5207,lng:-0.1021,hours:'Daily · Hours vary',open:true,indoor:true,station:'Farringdon · 6 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best/londons-top-100-restaurants_262',verified:'Featured in SquareMeal’s London Top 100 coverage; check reservations before visiting'},
  {id:'pizarro-bermondsey',categories:['restaurant'],name:'Pizarro',summary:'Spanish tapas restaurant on Bermondsey Street, serving seasonal small plates and sherry.',area:'Bermondsey',address:'194 Bermondsey Street, SE1 3TQ',lat:51.4998,lng:-0.0759,hours:'Daily · Hours vary',open:true,indoor:true,station:'London Bridge · 10 min',price:'££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/london',verified:'Listed in SquareMeal’s London restaurant guide; check opening hours before visiting'},
  {id:'padella-borough',categories:['restaurant'],name:'Padella',summary:'Fresh pasta restaurant by Borough Market with a concise Italian menu.',area:'South Bank',address:'6 Southwark Street, SE1 1TQ',lat:51.5044,lng:-0.0910,hours:'Daily · Hours vary',open:true,indoor:true,station:'London Bridge · 2 min',price:'££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/london',verified:'Listed in SquareMeal’s London restaurant guide; check walk-in and booking availability'},
  {id:'the-wolseley',categories:['restaurant'],name:'The Wolseley',summary:'Grand European-style café on Piccadilly for breakfast, afternoon tea and dinner.',area:'Mayfair',address:'160 Piccadilly, W1J 9EB',lat:51.5072,lng:-0.1401,hours:'Daily · Hours vary',open:true,indoor:true,station:'Green Park · 3 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/best-restaurants-in-london/',verified:'Included in SquareMeal’s London restaurant coverage; check reservations before visiting'},
  {id:'gymkhana',categories:['restaurant'],name:'Gymkhana',summary:'Refined Indian restaurant with regional dishes, grills and a club-like Mayfair setting.',area:'Mayfair',address:'42 Albemarle Street, W1S 4JH',lat:51.5124,lng:-0.1436,hours:'Daily · Hours vary',open:true,indoor:true,station:'Green Park · 5 min',price:'££££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best/londons-top-100-restaurants_262',verified:'Featured in SquareMeal’s London Top 100 coverage; check reservations before visiting'},
  {id:'blacklock-soho',categories:['restaurant'],name:'Blacklock Soho',summary:'Chophouse for charcoal-grilled chops, steaks and Sunday roasts in a former brothel.',area:'Soho',address:'24 Great Windmill Street, W1D 7LG',lat:51.5128,lng:-0.1331,hours:'Daily · Hours vary',open:true,indoor:true,station:'Piccadilly Circus · 3 min',price:'££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/london',verified:'Listed in SquareMeal’s London restaurant guide; check reservations before visiting'},
  {id:'manteca-shoreditch',categories:['restaurant'],name:'Manteca',summary:'Nose-to-tail Italian restaurant with handmade pasta, salumi and wood-fired cooking.',area:'Shoreditch',address:'49–51 Curtain Road, EC2A 3PT',lat:51.5238,lng:-0.0806,hours:'Daily · Hours vary',open:true,indoor:true,station:'Shoreditch High Street · 5 min',price:'£££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/london',verified:'Listed in SquareMeal’s London restaurant guide; check reservations before visiting'},
  {id:'lyles',categories:['restaurant'],name:'Lyle’s',summary:'Modern British restaurant in the Tea Building with a frequently changing seasonal menu.',area:'Shoreditch',address:'The Tea Building, 56 Shoreditch High Street, E1 6JJ',lat:51.5244,lng:-0.0782,hours:'Tue–Sat · Hours vary',open:true,indoor:true,station:'Shoreditch High Street · 2 min',price:'££££',source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best/londons-top-100-restaurants_262',verified:'Featured in SquareMeal’s London Top 100 coverage; check reservations before visiting'},
  {id:'the-devonshire',categories:['food-drink','restaurant'],name:'The Devonshire',summary:'A lively Soho pub with classic pints, a grill and a separate dining room.',area:'Soho',address:'17 Denman Street, W1D 7HW',lat:51.5111,lng:-0.1345,hours:'Daily · Hours vary',open:true,indoor:true,station:'Piccadilly Circus · 3 min',price:'££',isPub:true,source:'Tripadvisor',sourceLink:'https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d26844865-Reviews-The_Devonshire-London_England.html',verified:'Listed on Tripadvisor; check the pub for current walk-in and dining availability'},
  {id:'harwood-arms',categories:['food-drink','restaurant'],name:'The Harwood Arms',summary:'Michelin-starred Fulham gastropub focused on British game and seasonal produce.',area:'Kensington',address:'Walham Grove, SW6 1QP',lat:51.4807,lng:-0.1945,hours:'Daily · Hours vary',open:true,indoor:true,station:'Fulham Broadway · 8 min',price:'£££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check reservations before visiting'},
  {id:'anchor-and-hope',categories:['food-drink','restaurant'],name:'The Anchor & Hope',summary:'South Bank gastropub with a daily-changing menu and old-school pub atmosphere.',area:'South Bank',address:'36 The Cut, SE1 8LP',lat:51.5020,lng:-0.1088,hours:'Daily · Hours vary',open:true,indoor:true,station:'Waterloo · 6 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check service times before visiting'},
  {id:'george-inn',categories:['food-drink'],name:'The George Inn',summary:'National Trust galleried coaching inn near Borough Market, with historic courtyards and cask ale.',area:'South Bank',address:'77 Borough High Street, SE1 1NH',lat:51.5032,lng:-0.0913,hours:'Daily · Hours vary',open:true,indoor:true,station:'London Bridge · 5 min',price:'££',isPub:true,source:'Tripadvisor',sourceLink:'https://www.tripadvisor.co.uk/Restaurants-g186338-zfg11776-London_England.html',verified:'Listed in Tripadvisor’s London pub listings; check current opening times'},
  {id:'the-mayflower',categories:['food-drink'],name:'The Mayflower',summary:'Riverside Rotherhithe pub with a terrace, traditional interiors and views across the Thames.',area:'Rotherhithe',address:'117 Rotherhithe Street, SE16 4NF',lat:51.5013,lng:-0.0527,hours:'Daily · Hours vary',open:true,indoor:true,station:'Rotherhithe · 12 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check current opening times'},
  {id:'prospect-of-whitby',categories:['food-drink'],name:'The Prospect of Whitby',summary:'Historic Wapping pub on the Thames with a riverside terrace and classic pub food.',area:'Wapping',address:'57 Wapping Wall, E1W 3SH',lat:51.5086,lng:-0.0348,hours:'Daily · Hours vary',open:true,indoor:true,station:'Wapping · 9 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check current opening times'},
  {id:'french-house',categories:['food-drink'],name:'The French House',summary:'Historic Soho pub on Dean Street, known for French wine, conversation and a small dining room.',area:'Soho',address:'49 Dean Street, W1D 5BG',lat:51.5132,lng:-0.1313,hours:'Daily · Hours vary',open:true,indoor:true,station:'Tottenham Court Road · 5 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check current opening times'},
  {id:'ye-olde-cheshire-cheese',categories:['food-drink'],name:'Ye Olde Cheshire Cheese',summary:'A historic Fleet Street pub rebuilt after the Great Fire, with wood-panelled rooms and cellar bars.',area:'City of London',address:'145 Fleet Street, EC4A 2BU',lat:51.5139,lng:-0.1084,hours:'Daily · Hours vary',open:true,indoor:true,station:'Blackfriars · 6 min',price:'£',isPub:true,source:'Tripadvisor',sourceLink:'https://www.tripadvisor.co.uk/Restaurants-g186338-zfg11776-London_England.html',verified:'Listed in Tripadvisor’s London pub listings; check current opening times'},
  {id:'the-dove-hammersmith',categories:['food-drink'],name:'The Dove',summary:'Small riverside pub in Hammersmith with a long history, snug rooms and Thames-side tables.',area:'Hammersmith',address:'19 Upper Mall, W6 9TA',lat:51.4921,lng:-0.2280,hours:'Daily · Hours vary',open:true,indoor:true,station:'Ravenscourt Park · 11 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check current opening times'},
  {id:'the-holly-bush',categories:['food-drink'],name:'The Holly Bush',summary:'Cosy, historic Hampstead pub with fireplaces, British dishes and a tucked-away village setting.',area:'Hampstead',address:'22 Holly Mount, NW3 6SG',lat:51.5562,lng:-0.1765,hours:'Daily · Hours vary',open:true,indoor:true,station:'Hampstead · 8 min',price:'££',isPub:true,source:'SquareMeal',sourceLink:'https://www.squaremeal.co.uk/restaurants/best-for/best-pubs-in-london_9602',verified:'Included in SquareMeal’s London pub guide; check current opening times'},
  {id:'squares-restaurant-bar',categories:['restaurant','food-drink'],name:'Squares Restaurant & Bar',summary:'Trafalgar Square hotel restaurant and bar serving cocktails, wine, beer and all-day dining.',area:'Westminster',address:'1 Whitcomb Street, WC2H 7HG',lat:51.5098,lng:-0.1287,hours:'Daily · Hours vary',open:true,indoor:true,station:'Charing Cross · 3 min',price:'££',source:'Thistle Hotels',sourceLink:'https://www.thistle.com/trafalgar-square/wp-content/uploads/sites/5/2025/03/Thistle-Trafalgar-Square-SQUARES-Restaurant-Menu.pdf',verified:'Menu and venue details published by Thistle Hotels; check current service times'},
  {id:'cafe-kick',categories:['food-drink'],name:'Café Kick',summary:'Euro-style sports bar on Exmouth Market, with Spanish beer, vermouth and table football.',area:'Clerkenwell',address:'43 Exmouth Market, EC1R 4QL',lat:51.5274,lng:-0.1089,hours:'Daily · 12:00–00:00',open:true,indoor:true,station:'Farringdon · 10 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'No. 1 in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'jumbi',categories:['food-drink','music'],name:'Jumbi',summary:'Music-led Peckham bar with DJ sets, Caribbean flavours and a relaxed terrace-to-dancefloor mood.',area:'Peckham',address:'Unit 4.1, Copeland Park, 133 Copeland Road, SE15 3SN',lat:51.4742,lng:-0.0688,hours:'Tue–Sun · Hours vary',open:true,indoor:true,station:'Peckham Rye · 5 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check events and opening times'},
  {id:'ellies-dalston',categories:['food-drink'],name:'Ellie’s',summary:'Easy-going Dalston neighbourhood cocktail bar with pavement tables and a concise drinks list.',area:'Dalston',address:'428 Kingsland Road, E8 4AA',lat:51.5438,lng:-0.0747,hours:'Wed–Sun · Hours vary',open:true,indoor:true,station:'Haggerston · 8 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'umbrella-workshop',categories:['food-drink'],name:'Umbrella Workshop',summary:'Tiny Shoreditch cocktail workshop and test kitchen tucked down an alley near Boundary Street.',area:'Shoreditch',address:'Unit 10 Cleeve Workshops, Boundary Street, E2 7JD',lat:51.5268,lng:-0.0788,hours:'Daily · 12:00–22:00',open:true,indoor:true,station:'Shoreditch High Street · 7 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'waltz-shoreditch',categories:['food-drink'],name:'Waltz',summary:'Japanese cocktail bar in Shoreditch with a micro-seasonal menu and jazz soundtrack.',area:'Shoreditch',address:'28 Scrutton Street, EC2A 4RP',lat:51.5236,lng:-0.0848,hours:'Mon–Sat · Hours vary',open:true,indoor:true,station:'Old Street · 6 min',price:'£££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Time Out’s 2026 pick for best cocktail bar; check current opening times'},
  {id:'big-johns-biltong-bar',categories:['food-drink'],name:'Big John’s Biltong Bar',summary:'Friendly Deptford dive bar for cold beer, biltong and late-afternoon happy-hour pints.',area:'Deptford',address:'29 Deptford High Street, SE8 4AD',lat:51.4786,lng:-0.0251,hours:'Mon–Sun · Hours vary',open:true,indoor:true,station:'Deptford · 3 min',price:'£',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Time Out’s 2026 pick for best dive bar; check current opening times'},
  {id:'tramps-bar',categories:['food-drink','art-culture'],name:'Tramps Bar',summary:'Islington art-world bar with a compact kitchen, occasional DJs and a martini-focused drinks list.',area:'Islington',address:'15f Micawber Street, N1 7TB',lat:51.5306,lng:-0.0886,hours:'Mon, Wed–Fri · Hours vary',open:true,indoor:true,station:'Old Street · 8 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Time Out’s 2026 pick for best new bar; check current opening times'},
  {id:'rasputins-hackney',categories:['food-drink'],name:'Rasputin’s',summary:'Hackney dive-ish bar for good-value martinis, B-movies, hot dogs and themed nights.',area:'Hackney',address:'171 Mare Street, E8 3RH',lat:51.5463,lng:-0.0558,hours:'Tue–Sat · Hours vary',open:true,indoor:true,station:'Hackney Central · 6 min',price:'£',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'bonne-route',categories:['food-drink'],name:'Bonne Route',summary:'Crouch End natural wine bar with a cosy room, bottles to take away and small plates.',area:'Harringay',address:'42 Quernmore Road, N4 4QP',lat:51.5773,lng:-0.1070,hours:'Wed–Sat · Hours vary',open:true,indoor:true,station:'Harringay · 4 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Time Out’s 2026 pick for best wine bar; check current opening times'},
  {id:'equal-parts',categories:['food-drink'],name:'Equal Parts',summary:'Hackney Road listening bar with seasonal cocktails, a thoughtful no/low list and weekend coffee.',area:'Hackney',address:'245 Hackney Road, E2 8NA',lat:51.5329,lng:-0.0580,hours:'Daily · Hours vary',open:true,indoor:true,station:'Hoxton · 8 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'endeavour-deptford',categories:['food-drink','music'],name:'Endeavour',summary:'Independent Deptford dive bar with a basement performance space, comedy and late-night drinks.',area:'Deptford',address:'39 Deptford Broadway, SE8 4PQ',lat:51.4792,lng:-0.0250,hours:'Tue–Sun · Hours vary',open:true,indoor:true,station:'Deptford · 2 min',price:'£',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check events and opening times'},
  {id:'lower-wine-bar',categories:['food-drink'],name:'Lower Wine Bar',summary:'Parisian-style Waterloo wine bar with a strong by-the-glass list and a small food menu.',area:'South Bank',address:'19 Lower Marsh, SE1 7RJ',lat:51.5004,lng:-0.1127,hours:'Tue–Sat · Hours vary',open:true,indoor:true,station:'Waterloo · 4 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'},
  {id:'roses-of-elagabalus',categories:['food-drink','music'],name:'The Roses of Elagabalus',summary:'Dalston queer clubhouse with cabaret, rotating food pop-ups and classic cocktails.',area:'Dalston',address:'578 Kingsland Road, E8 4AH',lat:51.5487,lng:-0.0756,hours:'Tue–Sun · Hours vary',open:true,indoor:true,station:'Dalston Junction · 2 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check events and opening times'},
  {id:'cafe-1001',categories:['food-drink','music'],name:'Café 1001',summary:'Brick Lane café-bar that shifts from daytime coffee and brunch to DJs, beer and cocktails.',area:'Shoreditch',address:'91 Brick Lane, E1 6QL',lat:51.5213,lng:-0.0715,hours:'Daily · Hours vary',open:true,indoor:true,station:'Shoreditch High Street · 5 min',price:'££',source:'Time Out',sourceLink:'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london',verified:'Included in Time Out’s 2026 London bars guide; check current opening times'}
];
const timeOutGuide = 'https://www.timeout.com/london/bars-and-pubs/the-best-bars-in-london';
const timeOutBars = [
  ['upstairs-at-hausu','Upstairs at Hausu','Peckham','11a Station Way, SE15 4RX',51.4731,-0.0687,'4/5'],
  ['scarfes-bar','Scarfes Bar','Holborn','Rosewood London, 252 High Holborn, WC1V 7EN',51.5173,-0.1192,'5/5'],
  ['godet','Godet','Islington','382 Essex Road, N1 3PF',51.5482,-0.0783,'4/5'],
  ['bar-italia','Bar Italia','Soho','22 Frith Street, W1D 4RF',51.5137,-0.1335,'5/5'],
  ['next-door-records','Next Door Records','Shepherd’s Bush','304 Uxbridge Road, W12 7LJ',51.5075,-0.2291,'Not rated'],
  ['blondies','Blondies','Clapton','205A Lower Clapton Road, E5 8EG',51.5531,-0.0447,'5/5'],
  ['half-cut-market','Half Cut Market','Holloway','396 York Way, N7 9LW',51.5614,-0.1208,'5/5'],
  ['franks-cafe','Frank’s Cafe','Peckham','95a Rye Lane, SE15 4ST',51.4707,-0.0688,'5/5'],
  ['all-my-friends','All My Friends','Hackney Wick','Unit 1, Hamlet Estate, 96 White Post Lane, E9 5EN',51.5445,-0.0233,'4/5'],
  ['bar-lotus','Bar Lotus','Dalston','480 Kingsland Road, E8 4AE',51.5463,-0.0750,'5/5'],
  ['archive-and-myth','Archive & Myth','Leicester Square','Hippodrome Casino, Cranbourn Street, WC2H 7JH',51.5103,-0.1292,'4/5'],
  ['bauhaus-warehaus','Bauhaus Warehaus','Dalston','538 Kingsland Road, E8 4AH',51.5506,-0.0770,'4/5'],
  ['the-dover','The Dover','Mayfair','33 Dover Street, W1S 4NF',51.5094,-0.1475,'5/5'],
  ['jazu','Jazu','Deptford','2 Deptford High Street, SE8 4AF',51.4783,-0.0256,'4/5'],
  ['lowcountry','Lowcountry','Islington','71 Nile Street, N1 7RD',51.5300,-0.0882,'5/5'],
  ['helgis','Helgi’s','Hackney','177 Mare Street, E8 3RH',51.5465,-0.0556,'4/5'],
  ['three-sheets-soho','Three Sheets Soho','Soho','13 Manette Street, W1D 4AP',51.5162,-0.1322,'4/5'],
  ['le-beaujolais','Le Beaujolais','Covent Garden','25 Litchfield Street, WC2H 9NJ',51.5135,-0.1284,'5/5'],
  ['dive-marylebone','Dive','Marylebone','50–54 Blandford Street, W1U 7HX',51.5209,-0.1542,'3/5'],
  ['flying-w-saloon','Flying W Saloon','London Bridge','8 Snowsfields, SE1 3SU',51.4998,-0.0818,'4/5'],
  ['satans-whiskers','Satan’s Whiskers','Bethnal Green','343 Cambridge Heath Road, E2 9RA',51.5318,-0.0588,'5/5'],
  ['the-social','The Social','Fitzrovia','5 Little Portland Street, W1W 7JD',51.5176,-0.1413,'Not rated'],
  ['bloodsports','Bloodsports','Covent Garden','27–29 Endell Street, WC2H 9BA',51.5141,-0.1256,'4/5'],
  ['69-colebrooke-row','69 Colebrooke Row','Islington','69 Colebrooke Row, N1 8AA',51.5407,-0.1030,'5/5'],
  ['side-hustle','Side Hustle','Covent Garden','28 Bow Street, WC2E 7AW',51.5145,-0.1219,'4/5'],
  ['all-my-gods','All My Gods','Bethnal Green','253 Paradise Row, E2 9LE',51.5294,-0.0574,'4/5'],
  ['flipdog','FlipDog','Shoreditch','104–122 City Road, EC1V 2NR',51.5260,-0.0873,'5/5'],
  ['bar-flor','Bar Flor','Chelsea','Newsons Yard, 57 Pimlico Road, SW1W 8NE',51.4888,-0.1612,'Not rated'],
  ['ridley-road-market-bar','Ridley Road Market Bar','Dalston','49 Ridley Road, E8 2NP',51.5453,-0.0730,'4/5'],
  ['brutes-of-mayfair','Brutes of Mayfair','Mayfair','34A Bruton Place, W1J 6NR',51.5104,-0.1461,'5/5'],
  ['trishas','Trisha’s','Soho','57 Greek Street, W1D 3DX',51.5138,-0.1315,'5/5'],
  ['la-camionera','La Camionera','Hackney','243 Well Street, E9 6RG',51.5486,-0.0431,'4/5'],
  ['bar-americain','Bar Américain','Soho','20 Sherwood Street, W1F 7ED',51.5122,-0.1349,'5/5'],
  ['moto','Moto','Covent Garden','7 Maiden Lane, WC2E 7NA',51.5111,-0.1232,'4/5'],
  ['easy-8','Easy 8','Hackney','159A Mare Street, E8 3RD',51.5444,-0.0558,'4/5'],
  ['mascara-bar','Mascara Bar','Stoke Newington','72 Stamford Hill, N16 6XS',51.5680,-0.0755,'Not rated']
].map(([id,name,area,address,lat,lng,rating]) => ({id,categories:['food-drink'],name,summary:'Recommended London bar from Time Out’s 2026 guide.',area,address,lat,lng,hours:'Hours vary',open:true,indoor:true,station:'Check TfL journey planner',price:'££',source:'Time Out',sourceLink:timeOutGuide,rating:`Time Out · ${rating}`,verified:'Included in Time Out’s 2026 London bars guide; check current opening times'}));
items.push(...timeOutBars);
const timeOutRatings = { 'cafe-kick':'5/5',jumbi:'5/5','ellies-dalston':'4/5','umbrella-workshop':'5/5','waltz-shoreditch':'5/5','big-johns-biltong-bar':'5/5','tramps-bar':'5/5','rasputins-hackney':'4/5','bonne-route':'4/5','equal-parts':'5/5','endeavour-deptford':'5/5','lower-wine-bar':'5/5','roses-of-elagabalus':'4/5','cafe-1001':'4/5' };
items.forEach(item => { if(item.source === 'Time Out') { item.rating = item.rating || `Time Out · ${timeOutRatings[item.id] || 'Not rated'}`; item.summary += ` Time Out rating: ${item.rating.replace('Time Out · ','')}.`; } });
const touristSources = {
  londonMyMind: ['London On My Mind','https://londonmymind.com/must-see-london/'],
  tripadvisor: ['Tripadvisor','https://www.tripadvisor.co.uk/Attractions-g186338-Activities-London_England.html'],
  visitLondon: ['Visit London','https://www.visitlondon.com/']
};
const touristDestinations = [
  ['palace-of-westminster','Palace of Westminster & Big Ben','Westminster','Parliament Square, SW1A 0AA',51.4995,-0.1248,'Gothic riverside landmark, home to Parliament and the Elizabeth Tower.', 'londonMyMind',['art-culture']],
  ['westminster-abbey','Westminster Abbey','Westminster','Dean’s Yard, SW1P 3PA',51.4993,-0.1273,'Historic coronation church with royal tombs, memorials and Gothic architecture.', 'tripadvisor',['art-culture']],
  ['the-shard','The Shard','London Bridge','32 London Bridge Street, SE1 9SG',51.5045,-0.0865,'London’s tallest viewing platform, with wide skyline views from the upper floors.', 'londonMyMind',['experience']],
  ['tower-bridge','Tower Bridge','Tower Bridge','Tower Bridge Road, SE1 2UP',51.5055,-0.0754,'Victorian bascule bridge with high-level walkways and an engine-room exhibition.', 'tripadvisor',['art-culture']],
  ['tower-of-london','Tower of London','Tower Hill','EC3N 4AB',51.5081,-0.0761,'Historic royal fortress and home of the Crown Jewels.', 'tripadvisor',['art-culture','family-kids']],
  ['london-wall','London Wall','City of London','London Wall, EC2Y',51.5161,-0.0906,'Surviving fragments of the Roman wall that once enclosed the City of London.', 'londonMyMind',['art-culture']],
  ['the-monument','The Monument to the Great Fire of London','City of London','Monument Street, EC3R 8AH',51.5102,-0.0865,'A 17th-century column commemorating the Great Fire, with a viewing platform.', 'londonMyMind',['art-culture','experience']],
  ['leadenhall-market','Leadenhall Market','City of London','Gracechurch Street, EC3V 1LT',51.5127,-0.0836,'Ornate covered Victorian market with shops, cafés and a distinctive painted roof.', 'londonMyMind',['market-shopping','art-culture']],
  ['london-stone','London Stone','City of London','111 Cannon Street, EC4N 5AR',51.5107,-0.0868,'A small but storied ancient landmark preserved on Cannon Street.', 'londonMyMind',['art-culture']],
  ['st-pauls-cathedral','St Paul’s Cathedral','City of London','St Paul’s Churchyard, EC4M 8AD',51.5138,-0.0984,'Wren’s great cathedral, famous for its dome, crypt and Whispering Gallery.', 'londonMyMind',['art-culture']],
  ['st-pancras-international','St Pancras International','King’s Cross','Euston Road, N1C 4QP',51.5318,-0.1261,'Grand Victorian railway station with a celebrated clock tower and Eurostar services.', 'londonMyMind',['art-culture']],
  ['kings-cross-station','King’s Cross Station','King’s Cross','Euston Road, N1 9AL',51.5308,-0.1238,'Major rail hub beside Coal Drops Yard and the Harry Potter photo spot.', 'londonMyMind',['market-shopping']],
  ['platform-nine-and-three-quarters','Platform 9¾','King’s Cross','King’s Cross Station, N1 9AL',51.5309,-0.1240,'Harry Potter-themed photo opportunity and shop inside King’s Cross Station.', 'londonMyMind',['family-kids','experience']],
  ['sherlock-holmes-museum','Sherlock Holmes Museum','Marylebone','221b Baker Street, NW1 6XE',51.5238,-0.1585,'Period house museum inspired by the fictional detective’s Baker Street rooms.', 'londonMyMind',['art-culture','family-kids']],
  ['royal-observatory','Royal Observatory Greenwich','Greenwich','Blackheath Avenue, SE10 8XJ',51.4774,0.0000,'Home of the Prime Meridian, historic telescopes and hilltop views across London.', 'londonMyMind',['art-culture','experience']],
  ['natural-history-museum','Natural History Museum','Kensington','Cromwell Road, SW7 5BD',51.4967,-0.1764,'Free museum of the natural world, known for its grand hall and dinosaur displays.', 'tripadvisor',['art-culture','family-kids','indoor']],
  ['victoria-and-albert-museum','V&A South Kensington','Kensington','Cromwell Road, SW7 2RL',51.4966,-0.1722,'World-leading museum of art, design and performance, with free permanent collections.', 'tripadvisor',['art-culture','indoor']],
  ['science-museum','Science Museum','Kensington','Exhibition Road, SW7 2DD',51.4978,-0.1745,'Hands-on science museum with family galleries, engineering collections and IMAX cinema.', 'visitLondon',['art-culture','family-kids','indoor']],
  ['sky-garden','Sky Garden','City of London','1 Sky Garden Walk, EC3M 8AF',51.5111,-0.0836,'Public indoor garden and viewing level at the top of 20 Fenchurch Street.', 'tripadvisor',['experience','indoor']],
  ['covent-garden','Covent Garden','Covent Garden','Covent Garden Piazza, WC2E 8RF',51.5117,-0.1230,'Historic piazza for street performers, shopping, dining and theatre.', 'tripadvisor',['market-shopping','food-drink']],
  ['shakespeares-globe','Shakespeare’s Globe','South Bank','21 New Globe Walk, SE1 9DT',51.5081,-0.0972,'Reconstructed open-air theatre with performances, exhibitions and guided tours.', 'tripadvisor',['theatre-comedy','art-culture']],
  ['royal-albert-hall','Royal Albert Hall','Kensington','Kensington Gore, SW7 2AP',51.5009,-0.1774,'Landmark concert hall with tours and a year-round programme of performances.', 'tripadvisor',['music','art-culture']],
  ['tate-modern','Tate Modern','South Bank','Bankside, SE1 9TG',51.5076,-0.1002,'Free modern-art museum in the former Bankside Power Station.', 'tripadvisor',['art-culture','indoor']],
  ['tate-britain','Tate Britain','Westminster','Millbank, SW1P 4RG',51.4908,-0.1279,'National collection of British art from 1500 to the present day.', 'visitLondon',['art-culture','indoor']],
  ['kew-gardens','Royal Botanic Gardens, Kew','Kew','Kew, TW9 3AB',51.4787,-0.2956,'World-famous botanic gardens with glasshouses, treetop walkways and broad landscapes.', 'tripadvisor',['parks-outdoors','family-kids']],
  ['buckingham-palace','Buckingham Palace','Westminster','London, SW1A 1AA',51.5014,-0.1419,'Official London residence of the monarch, with seasonal State Rooms visits.', 'visitLondon',['art-culture','experience']],
  ['churchill-war-rooms','Churchill War Rooms','Westminster','King Charles Street, SW1A 2AQ',51.5022,-0.1295,'Underground wartime command centre and museum dedicated to Winston Churchill.', 'visitLondon',['art-culture','indoor']],
  ['imperial-war-museum','Imperial War Museum London','South Bank','Lambeth Road, SE1 6HZ',51.4958,-0.1081,'Museum exploring conflicts from the First World War to the present day.', 'visitLondon',['art-culture','family-kids','indoor']],
  ['madame-tussauds','Madame Tussauds London','Marylebone','Marylebone Road, NW1 5LR',51.5230,-0.1551,'Immersive wax-figure attraction featuring film, music, sport and history icons.', 'visitLondon',['family-kids','experience','indoor']],
  ['sea-life-london','SEA LIFE London Aquarium','South Bank','County Hall, SE1 7PB',51.5021,-0.1195,'Riverside aquarium with marine habitats, sharks, rays and family displays.', 'visitLondon',['family-kids','experience','indoor']],
  ['kensington-palace','Kensington Palace','Kensington','Kensington Gardens, W8 4PX',51.5050,-0.1877,'Royal palace in Kensington Gardens with historic royal apartments and exhibitions.', 'tripadvisor',['art-culture','family-kids']],
  ['zsl-london-zoo','ZSL London Zoo','Regent’s Park','Outer Circle, NW1 4RY',51.5353,-0.1534,'Regent’s Park zoo with animal habitats, talks and family-focused experiences.', 'visitLondon',['family-kids','experience','parks-outdoors']],
  ['cutty-sark','Cutty Sark','Greenwich','King William Walk, SE10 9HT',51.4826,-0.0096,'Historic tea clipper in Greenwich, now an interactive maritime museum.', 'visitLondon',['art-culture','family-kids']],
  ['hms-belfast','HMS Belfast','London Bridge','The Queen’s Walk, SE1 2JH',51.5065,-0.0816,'Second World War warship museum moored on the Thames near Tower Bridge.', 'visitLondon',['art-culture','family-kids']],
  ['earls-court-police-box','Earl’s Court Police Box','Kensington','Earl’s Court Road, SW5',51.4916,-0.1933,'Blue police-box landmark and a popular Doctor Who photo stop near Earl’s Court.', 'londonMyMind',['art-culture','family-kids']],
  ['london-telephone-boxes','Iconic Red Telephone Boxes','Westminster','Great George Street, SW1P 3AA',51.5004,-0.1288,'Classic red telephone boxes near Westminster make a quintessential London photo stop.', 'londonMyMind',['art-culture']],
  ['shoreditch-street-art','Shoreditch Street Art','Shoreditch','Brick Lane, E1 6QL',51.5213,-0.0715,'Ever-changing murals, paste-ups and independent galleries across Shoreditch and Brick Lane.', 'londonMyMind',['art-culture','parks-outdoors']],
  ['whitechapel-history-walk','Whitechapel History Walk','Whitechapel','Whitechapel High Street, E1 7QA',51.5169,-0.0658,'Self-guided East End walk for Victorian history, including the locations associated with Jack the Ripper.', 'londonMyMind',['art-culture','experience']]
].map(([id,name,area,address,lat,lng,summary,sourceKey,extraCategories]) => ({id,categories:['tourist-place',...extraCategories],name,summary,area,address,lat,lng,hours:'Hours vary',open:true,indoor:extraCategories.includes('indoor'),family:extraCategories.includes('family-kids'),station:'Check TfL journey planner',price:'Varies',source:touristSources[sourceKey][0],sourceLink:touristSources[sourceKey][1],verified:`Featured in the ${touristSources[sourceKey][0]} London visitor guide; check current opening times and ticket requirements`}));
items.push(...touristDestinations);
const touristCompatibleCategories = new Set(['art-culture','market-shopping','parks-outdoors','experience']);
items.forEach(item => { if(item.categories.some(category => touristCompatibleCategories.has(category)) && !item.categories.includes('tourist-place')) item.categories.push('tourist-place'); });
const sourceStatuses = [
  ['Curated London locations','Pins include visitor destinations from London On My Mind, Tripadvisor and Visit London, plus restaurant and bar recommendations from SquareMeal, Thistle Hotels and Time Out. Always check the linked venue for current hours and tickets.','Available'],
  ['OpenStreetMap base map','© OpenStreetMap contributors. Tiles must be used within the selected provider’s policy. Retention: none.','Configured'],
  ['Live city updates','BBC London News, City of London, London City Hall, TfL and Open-Meteo are requested by the local server whenever the page opens.','Live']
];
let map, markers = {}, stationMarkers = [], selectedId = null, stationsVisible = true, selectedDate = 'today', planMode = false;
let saved = JSON.parse(localStorage.getItem('lvc-saved') || '[]');
const el = id => document.getElementById(id);

function init() {
  renderCategories(); renderTicker(); renderSources(); initMap(); bindEvents(); applyFilters(); updateSavedCount(); loadLiveUpdates();
}
function renderCategories() { el('categoryOptions').innerHTML = categories.map(c => { const count=items.filter(item=>item.categories.includes(c.id)).length; return `<label class="category-option"><input type="checkbox" value="${c.id}" class="category-check"><i class="cat-swatch" style="background:${c.color}"></i><span>${c.label}</span><b class="category-count">${count}</b></label>`; }).join(''); el('mapLegend').innerHTML = categories.slice(0,7).map(c => `<span class="legend-item"><i style="background:${c.color}"></i>${c.label.replace(' &','')}</span>`).join(''); }
function renderTicker(updates=[]) { const cards=(updates.length ? updates : [{type:'↻',source:'Live updates',text:'Loading London news, events, travel and weather…',url:'#',time:'Now'}]); el('tickerTrack').innerHTML=[...cards,...cards].map(({type,source,text,url,time})=>`<span class="ticker-item"><span class="ticker-type">${type}</span><time>${time || 'Now'}</time><b>${source}</b><a href="${url}" target="_blank" rel="noreferrer">${text} ↗</a></span>`).join(''); }
function renderSources(lastUpdated='—') { el('sourceList').innerHTML = sourceStatuses.map(([name,desc,status]) => `<div class="source-row"><div><h3>${name}</h3><p>${desc}<br>Last successful fetch: ${name === 'Live city updates' ? lastUpdated : '—'}</p></div><span class="source-status">${status}</span></div>`).join(''); }
async function loadLiveUpdates(force=false) {
  const button=el('refreshAlerts'); button.classList.add('loading'); button.disabled=true;
  try {
    const response=await fetch(`/api/updates${force ? '?refresh=1' : ''}`,{headers:{Accept:'application/json'}});
    if(!response.ok) throw new Error(`Update request failed (${response.status})`);
    const payload=await response.json();
    renderTicker(payload.updates || []); renderSources(payload.updatedAt || 'just now');
    button.innerHTML=`<span aria-hidden="true">↻</span> Updated ${payload.updatedAt || 'just now'}`;
  } catch (error) {
    renderTicker([{type:'!',source:'Updates unavailable',text:'Live updates are temporarily unavailable. Please try again shortly.',url:'#',time:'Now'}]);
    button.innerHTML='<span aria-hidden="true">↻</span> Retry updates';
  } finally { button.classList.remove('loading'); button.disabled=false; }
}
function initMap() {
  map = L.map('map',{zoomControl:false,attributionControl:false,preferCanvas:true}).setView([51.505,-0.107],12);
  L.control.zoom({position:'bottomright'}).addTo(map);
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(map);
  items.forEach(item => { const cat = categoryById[item.categories[0]]; const icon=L.divIcon({className:'custom-pin',html:`<div class="pin" style="--pin:${cat.color}"><span>${cat.icon}</span></div>`,iconSize:[35,35],iconAnchor:[17,35]}); const marker=L.marker([item.lat,item.lng],{icon,keyboard:true,title:item.name,alt:item.name}).addTo(map).bindTooltip(`${item.name}<br><small>${item.area} · ${item.price}</small>`,{direction:'top',offset:[0,-28],opacity:.96}); marker.on('click',()=>selectItem(item.id,true)); markers[item.id]=marker; });
  [[51.5009,-.1246],[51.530,-.123],[51.514,-.149],[51.501,-.094],[51.528,-.081],[51.489,-.009]].forEach(([lat,lng])=> { const m=L.marker([lat,lng],{icon:L.divIcon({className:'custom-pin',html:'<i class="station-dot"></i>',iconSize:[12,12],iconAnchor:[6,6]}),interactive:false}).addTo(map); stationMarkers.push(m); });
}
function localDate(value=new Date()) { const offset=value.getTimezoneOffset()*60000; return new Date(value-offset).toISOString().slice(0,10); }
function dateFromInput(value) { return new Date(`${value}T12:00:00`); }
function eventMatchesSelectedDate(item) { if(!item.event) return true; const weekdays=item.eventWeekdays || []; if(selectedDate==='weekend') { const today=new Date().getDay(); const weekendDays=today===0 ? [0] : [6,0]; return weekendDays.some(day=>weekdays.includes(day)); } const date=selectedDate==='custom' ? dateFromInput(el('customDate').value) : new Date(); return weekdays.includes(date.getDay()); }
function currentFiltered() { if(planMode) return saved.map(id=>items.find(item=>item.id===id)).filter(Boolean); const query=el('searchInput').value.trim().toLowerCase(); const cats=[...document.querySelectorAll('.category-check:checked')].map(x=>x.value); const f=Object.fromEntries([...document.querySelectorAll('[data-filter]')].map(x=>[x.dataset.filter,x.checked])); const area=el('areaSelect').value; return items.filter(item => { const hay=`${item.name} ${item.summary} ${item.area} ${item.categories.map(c=>categoryById[c].label).join(' ')}`.toLowerCase(); if(query && !hay.includes(query)) return false; if(cats.length && !item.categories.some(c=>cats.includes(c))) return false; if(f.free&&!item.free||f.open&&!item.open||f.family&&!item.family||f.stepfree&&!item.stepfree||f.indoor&&!item.indoor||f.station&&!item.station) return false; if(area && item.area!==area) return false; return eventMatchesSelectedDate(item); }); }
function applyFilters() { const filtered=currentFiltered(), ids=new Set(filtered.map(i=>i.id)), total=items.length; Object.entries(markers).forEach(([id,marker])=> { if(ids.has(id)) marker.addTo(map); else marker.remove(); }); el('resultCount').textContent=planMode?`${filtered.length} saved ${filtered.length===1?'place':'places'}`:`${filtered.length} of ${total} places`; el('mapResultCount').textContent=planMode?`${filtered.length} saved`:`${filtered.length} shown`; el('planMapNotice').hidden=!planMode; el('resultList').innerHTML=filtered.length?filtered.map(item=>{const c=categoryById[item.categories[0]];return `<button class="result-card ${selectedId===item.id?'selected':''}" data-id="${item.id}"><span class="result-icon" style="background:${c.color}">${c.icon}</span><span><strong>${item.name}</strong><small>${item.area} · ${item.price}</small></span><span>›</span></button>`}).join(''):`<p class="result-empty">No exact matches. Clear a filter to browse all ${total} places.</p>`; if(selectedId&&!ids.has(selectedId)) closeDetail(); }
function selectItem(id,pan=false) { const item=items.find(x=>x.id===id); if(!item)return; selectedId=id; document.querySelectorAll('.pin.selected').forEach(pin=>pin.classList.remove('selected')); const pin=markers[id]?.getElement()?.querySelector('.pin'); if(pin) pin.classList.add('selected'); if(pan) map.panTo([item.lat,item.lng]); renderDetail(item); el('detailPanel').classList.add('open'); applyFilters(); }
function renderDetail(item) { const content=el('detailContent'); const node=el('detailTemplate').content.cloneNode(true); const c=categoryById[item.categories[0]]; node.querySelector('.detail-hero').style.setProperty('--category',c.color); node.querySelector('.detail-category').textContent=c.label; node.querySelector('.hero-icon').textContent=c.icon; node.querySelector('.detail-kicker').textContent=item.area+(item.event?' · Event venue':' · Place'); node.querySelector('h2').textContent=item.name; node.querySelector('.detail-summary').textContent=item.summary; const st=node.querySelector('.status-line'); st.textContent='◷ '+item.hours; st.classList.add('closed'); const facts=[['When',item.hours],['Where',item.address],['Price',item.price],...(item.rating ? [['Guide rating',item.rating]] : []),['Access',item.stepfree?'Step-free access':'Check with venue'],['Coordinates',`${item.lat.toFixed(4)}, ${item.lng.toFixed(4)}`]]; node.querySelector('.fact-list').innerHTML=facts.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join(''); const tflDestination=encodeURIComponent(item.address); node.querySelector('.detail-actions').innerHTML=`<a href="https://www.openstreetmap.org/directions?to=${item.lat}%2C${item.lng}" target="_blank" rel="noreferrer">Directions ↗</a><a class="secondary" href="https://tfl.gov.uk/plan-a-journey/?to=${tflDestination}" target="_blank" rel="noreferrer">Plan with TfL ↗</a>`; node.querySelector('.nearby-station').innerHTML=`<b>Nearby transport</b>Ⓜ ${item.station || 'Travel information to be confirmed'}<br><span>Use the official TfL planner for live routes.</span>`; node.querySelector('.provenance').innerHTML=`Source: <a href="${item.sourceLink}" target="_blank" rel="noreferrer">${item.source} ↗</a><br>${item.verified} · <a href="mailto:stale@example.invalid?subject=Stale%20information%3A%20${encodeURIComponent(item.name)}">Report stale information</a>`; const save=node.querySelector('.save-round'); const isSaved=saved.includes(item.id); save.textContent=isSaved?'♥':'♡'; save.classList.toggle('saved',isSaved); save.setAttribute('aria-label',isSaved?`Remove ${item.name} from itinerary`:`Save ${item.name} to itinerary`); save.addEventListener('click',()=>toggleSaved(item.id)); node.querySelector('.close-detail').addEventListener('click',closeDetail); content.replaceChildren(node); content.hidden=false; el('emptyDetail').hidden=true; }
function closeDetail() { selectedId=null; el('detailContent').hidden=true; el('detailContent').replaceChildren(); el('emptyDetail').hidden=false; el('detailPanel').classList.remove('open'); document.querySelectorAll('.pin.selected').forEach(pin=>pin.classList.remove('selected')); applyFilters(); }
function toggleSaved(id) { saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id]; localStorage.setItem('lvc-saved',JSON.stringify(saved)); updateSavedCount(); const selected=items.find(x=>x.id===selectedId); if(selected)renderDetail(selected); renderItinerary(); }
function updateSavedCount() { el('savedCount').textContent=saved.length; }
function openItinerary() { renderItinerary(); el('itineraryDialog').showModal(); }
function renderItinerary() { const list=el('itineraryList'); const plan=saved.map(id=>items.find(x=>x.id===id)).filter(Boolean); list.innerHTML=plan.map((x,index)=>`<li><span>${x.name}<small> · ${x.area}</small></span><span><button data-move="up" data-index="${index}" aria-label="Move ${x.name} earlier">↑</button><button data-move="down" data-index="${index}" aria-label="Move ${x.name} later">↓</button><button data-remove="${x.id}" aria-label="Remove ${x.name}">×</button></span></li>`).join(''); el('itineraryEmpty').hidden=plan.length>0; el('clearItinerary').hidden=plan.length===0; el('exportItinerary').disabled=plan.length===0; }
function resetAll() { planMode=false; document.querySelectorAll('input[type="checkbox"]').forEach(x=>x.checked=false); el('searchInput').value='';el('areaSelect').value='';selectedDate='today';el('customDateControl').hidden=true;document.querySelectorAll('.date-selector button').forEach((x,i)=>x.classList.toggle('active',i===0));applyFilters(); }
function showSavedPlanOnMap() { planMode=true; el('filters').classList.remove('open'); el('mobileFiltersButton').setAttribute('aria-expanded','false'); applyFilters(); const plan=currentFiltered(); if(plan.length) map.fitBounds(L.latLngBounds(plan.map(item=>[item.lat,item.lng])),{padding:[48,48],maxZoom:14}); else map.setView([51.505,-.107],12); setTimeout(()=>map.invalidateSize(),0); }
function bindEvents() {
  el('customDate').value=localDate(); document.addEventListener('input',e=>{if(e.target.matches('#searchInput'))applyFilters();}); document.addEventListener('change',e=>{if(e.target.matches('.category-check,[data-filter]'))applyFilters();}); el('areaSelect').addEventListener('change',applyFilters); el('customDate').addEventListener('change',applyFilters); document.querySelectorAll('.date-selector button').forEach(btn=>btn.addEventListener('click',()=>{selectedDate=btn.dataset.date;el('customDateControl').hidden=selectedDate!=='custom';document.querySelectorAll('.date-selector button').forEach(x=>x.classList.toggle('active',x===btn));applyFilters();})); el('clearFilters').addEventListener('click',resetAll);
  el('resultList').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)selectItem(b.dataset.id,true);}); el('resetMap').addEventListener('click',()=>map.setView([51.505,-.107],12));el('stationToggle').addEventListener('click',e=>{stationsVisible=!stationsVisible;stationMarkers.forEach(m=>stationsVisible?m.addTo(map):m.remove());e.currentTarget.setAttribute('aria-pressed',String(stationsVisible));});
  el('locateButton').addEventListener('click',()=>{if(!navigator.geolocation){alert('Location is not available in this browser.');return;}navigator.geolocation.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],14);L.circleMarker([p.coords.latitude,p.coords.longitude],{radius:8,color:'#101d35',fillColor:'#d8ff5c',fillOpacity:1}).addTo(map).bindTooltip('Your approximate location').openTooltip();},()=>alert('Location permission was not granted. Your location is not stored.'));});
  el('tickerControl').addEventListener('click',e=>{const paused=el('tickerTrack').classList.toggle('paused');e.currentTarget.textContent=paused?'▶':'Ⅱ';e.currentTarget.setAttribute('aria-label',paused?'Play updates':'Pause updates');}); el('refreshAlerts').addEventListener('click',()=>loadLiveUpdates(true));
  el('sourcesButton').addEventListener('click',()=>el('sourcesDialog').showModal());el('itineraryButton').addEventListener('click',openItinerary);el('returnToFilters').addEventListener('click',resetAll);document.querySelectorAll('[data-close-dialog]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  el('itineraryList').addEventListener('click',e=>{const remove=e.target.dataset.remove, move=e.target.dataset.move; if(remove)toggleSaved(remove);if(move){const i=+e.target.dataset.index,j=move==='up'?i-1:i+1;if(j>=0&&j<saved.length){[saved[i],saved[j]]=[saved[j],saved[i]];localStorage.setItem('lvc-saved',JSON.stringify(saved));renderItinerary();}}});el('clearItinerary').addEventListener('click',()=>{saved=[];localStorage.removeItem('lvc-saved');updateSavedCount();renderItinerary();if(selectedId)renderDetail(items.find(x=>x.id===selectedId));});el('exportItinerary').addEventListener('click',()=>{const plan=saved.map((id,i)=>`${i+1}. ${items.find(x=>x.id===id)?.name}`).join('\n');navigator.clipboard?.writeText(`My London day\n${plan}`);el('exportItinerary').textContent='Copied to clipboard';setTimeout(()=>el('exportItinerary').textContent='Export day plan',1200);});
  el('mobileFiltersButton').addEventListener('click',()=>{el('filters').classList.add('open');el('mobileFiltersButton').setAttribute('aria-expanded','true');});el('closeFilters').addEventListener('click',()=>{el('filters').classList.remove('open');el('mobileFiltersButton').setAttribute('aria-expanded','false');});
}
init();
